services:
  dbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dds2023
    volumes:
      - ./posgresdb:/var/lib/postgresql/data

  app:
    image: ddsdeploy
    restart: always
    ports:
      - 8080:8080
    environment:
        hibernate__connection__driver_class: org.postgresql.Driver
        hibernate__connection__password: root
        hibernate__connection__username: postgres
        hibernate__hbm2ddl__auto: update
        hibernate__connection__url: jdbc:postgresql://dbservice/dds2023
    depends_on:
      - dbservice

