services:
  dbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dds2023
    ports:
      - "5432:5432"
    volumes:
      - ./posgresdb:/var/lib/postgresql/data

  app:
    image: sha256:f6e17f86e1e8ddffe51d5ffaf7462b955a4a81f52e5de62bd987d2e36ae70e41
    restart: always
    ports:
      - 8080:8080
    environment:
        hibernate__connection__driver_class: org.postgresql.Driver
        hibernate__connection__password: root
        hibernate__connection__username: postgres
        hibernate__hbm2ddl__auto: update
        hibernate__connection__url: jdbc:postgresql://dbservice/dds2023
    depends_on:
      - dbservice

